### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by tony-schumacher** [trquoccuong/node-wave#1]
Hi, 

can you help me? I have the newest Node version and can't install your package.

gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/cassini/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/cassini/.nvm/versions/node/v7.5.0/bin/node" "/Users/cassini/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cassini/Node/artcollab/node_modules/canvas
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/cassini/.nvm/versions/node/v7.5.0/bin/node" "/Users/cassini/.nvm/versions/node/v7.5.0/bin/npm" "install" "--save" "node-wave"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cassini/Node/artcollab/npm-debug.log

**Comment by trquoccuong** [comment]
Hi you should install some node-canvas dependencies . Flow this installation https://github.com/Automattic/node-canvas
